version: '3'

services:
  db:
    image: postgres
  node:
    image: node
    command: bash -c "cd /frontend/frontend && yarn --no-bin-links && ./node_modules/.bin/react-scripts start"
    volumes: 
      - .:/frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
  web:
    build: .
    command: bash -c "sleep 5 && psql -p 5432 -U postgres -h db -f /server/server/db.sql && python /server/server/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/server
    ports:
      - "8000:8000"
    depends_on:
      - db